# Generated by Django 5.0 on 2024-02-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_transaction_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountnigerian',
            name='bank_code',
            field=models.CharField(choices=[('044', 'Access Bank'), ('058', 'Guaranty Trust Bank'), ('232', 'Sterling Bank'), ('033', 'Union Bank Nigeria Plc'), ('057', 'Zenith Bank'), ('063', 'Diamond Bank Plc'), ('050', 'Ecobank Nigeria'), ('084', 'Enterprise Bank Plc'), ('070', 'Fidelity Bank Plc'), ('011', 'First Bank of Nigeria Plc'), ('214', 'First City Monument Bank'), ('030', 'Heritage Banking Company Ltd'), ('301', 'Jaiz Bank'), ('082', 'Keystone Bank Ltd'), ('014', 'Mainstreet Bank Plc'), ('076', 'Skye Bank Plc'), ('039', 'Stanbic IBTC Plc'), ('232', 'Sterling Bank Plc'), ('032', 'Union Bank Nigeria Plc'), ('215', 'Unity Bank Plc'), ('035', 'WEMA Bank Plc')], default='058', max_length=20),
        ),
    ]
