# Generated by Django 5.0 on 2024-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountforeign',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollars'), ('GBP', 'British Pounds'), ('EUR', 'Euros')], default='USD', max_length=20),
        ),
    ]
