# Generated by Django 5.0 on 2024-03-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankaccountforeign_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountforeign',
            name='city',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountforeign',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountforeign',
            name='street_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountforeign',
            name='street_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
