# Generated by Django 5.0 on 2024-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bankaccountforeign_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountforeign',
            name='beneficiary_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
