# Generated by Django 5.0 on 2024-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bankaccountforeign_beneficiary_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountforeign',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccountnigerian',
            name='account_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
