# Generated by Django 5.0 on 2024-03-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_bankaccountforeign_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoplan',
            name='reference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
