# Generated by Django 5.0 on 2024-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_autoplan_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoplan',
            name='amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
